[package]
name = "moxi_bpt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.12"
moxi_mesh_utils = { path = "../moxi_mesh_utils" }
moxi_utils = { path = "../moxi_utils" }
